language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "K04/gO1d2dZG4LgrmfiCJdP0tNKciCmYyoWaenr8KODn6iz9vo8jBNMFyzfaFsehgHKJEnWf5xDVXhdF8oynNeXFuJTAamIs/tiVyleABTUnFty6vJuGp9VQtPmzuAkKnuVB6xnFxoO7arn8HqFIPnsLh23EKft+8/xQtmu8bywmkI5FSAm5omwwtAFTSWjSUj3QX2Cixegs7rR9kiYifsxaYCVx/UIHCJqRxSDuq9ToCXfbzmoeNH1HRWAsjwgRTAB3O/uBzA5OxVloDD1QzRhaF3Zh7Ph9D8BA7uIDbdxaaguY96VgaswclRe+BOfX1g98GhtZRWrPMUqJ3l8zvczhhzHviqQpwm8+1a9Xhn3N9S7BVsRpNK+bjIHu9ULqCSQ7NTJyE/dUR+c/lsv3HNqg4cj3yz2ielgqrqh9TQg0dVBfrkbviLu+DtFd5kXslc+WC2X/uwaRRIJxS+mznmyDaFlqvnvV3Ii3nQRqj1U1kjfkToosBfUWCo6v8I1MGRdnmj3nE2S4JGVPFqg7EVdBDodztBCkme2PZ98tFdoVNLOZx4FPb7wlkqUlyJ/1Zd4dr9HzmZjyXqAcWu4PKvJF6z51j4gEU1woXycb03bwMEaEZ3fzBI7ztjEhsb/11tUpxY/9l+NqubyL7LUCQPL2Corw89l7Npr5ccIa0x4="
